services:
  laravel-api:
    build: ./docker/php-fpm
    image: laravel-php-8.2
    container_name: laravel-api
    restart: unless-stopped
    volumes:
      - ./:/var/www/html
    networks:
      - laravel-network-link

  laravel-nginx:
    image: nginx:latest
    container_name: laravel-nginx
    restart: unless-stopped
    ports:
      - "8000:80"
    volumes:
      - ./:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - laravel-network-link
    depends_on:
      - laravel-api

  laravel-mysql:
    image: mysql:5.7
    container_name: ${DB_HOST}
    restart: unless-stopped
    ports:
      - "3360:3306"
    environment:
      MYSQL_DATABASE: '${DB_DATABASE}'
      MYSQL_USER: '${DB_USERNAME}'
      MYSQL_PASSWORD: '${DB_PASSWORD}'
      MYSQL_ROOT_PASSWORD: '${DB_ROOT_PASSWORD}'
    networks:
      - laravel-network-link
    volumes:
      - database-data:/var/lib/mysql

networks:
  laravel-network-link:
    driver: bridge
    name: laravel-network-link

volumes:
  database-data:
    name: laravel-mysql-database
